In [1]:
#1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

In [2]:
vertical_stack = np.vstack((A, B))
print("Vertical Stack:\n", vertical_stack)

Vertical Stack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
horizontal_stack = np.hstack((A, B))
print("Horizontal Stack:\n", horizontal_stack)

Horizontal Stack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [4]:
#2. Find common elements between A and B. [Hint : Intersection of two sets]

import numpy as np

# Define two arrays A and B
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[4, 5, 6],
              [7, 8, 9]])

# Find common elements (intersection of A and B)
common_elements = np.intersect1d(A, B)
print("Common Elements between A and B:", common_elements)

Common Elements between A and B: [4 5 6]


In [5]:
#3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

import numpy as np

# Define array A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Specify the range (between 5 and 10)
lower_bound = 5
upper_bound = 10

# Use np.where() to get the indices of elements between 5 and 10
indices = np.where((A >= lower_bound) & (A < upper_bound))

# Extract elements using the indices
numbers_in_range = A[indices]
print("Numbers in A between 5 and 10 using np.where():", numbers_in_range)

Numbers in A between 5 and 10 using np.where(): [5 6 7 8 9]


In [7]:
""" 4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3]) """

import numpy as np

# Load the Iris dataset from the URL
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

# Filter rows where petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

# Print the filtered rows
print("Filtered Rows:\n", filtered_rows)

Filtered Rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [8]:
""" 5. From df filter the 'Manufacturer', 'Model' and 'Type' for every
20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
"""
import pandas as pd

# Load the dataset
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Filter 'Manufacturer', 'Model', and 'Type' for every 20th row starting from row 0
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

# Display the filtered rows
print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [9]:
"""6. Replace missing values in Min.Price and Max.Price columns with
their respective mean.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
""" 

import pandas as pd

# Load the dataset
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Calculate the mean of Min.Price and Max.Price, ignoring NaN values
min_price_mean = df['Min.Price'].mean()
max_price_mean = df['Max.Price'].mean()

# Replace missing values in Min.Price and Max.Price with their respective mean using .loc[]
df.loc[df['Min.Price'].isna(), 'Min.Price'] = min_price_mean
df.loc[df['Max.Price'].isna(), 'Max.Price'] = max_price_mean

# Display the first few rows to verify
print(df[['Min.Price', 'Max.Price']].head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [10]:
"""7. How to get the rows of a dataframe with row sum > 100?
```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
"""

import pandas as pd
import numpy as np

# Create a DataFrame with random integers between 10 and 40
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Calculate the row sums
row_sums = df.sum(axis=1)

# Filter rows where the row sum is greater than 100
filtered_rows = df[row_sums > 100]

# Display the filtered rows
print("Rows with row sum greater than 100:\n", filtered_rows)

Rows with row sum greater than 100:
      0   1   2   3
5   23  37  25  34
6   39  26  20  18
7   37  38  24  16
8   21  33  23  37
9   19  37  35  26
10  36  15  28  22
